apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-kafka
  namespace: apache-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-kafka
  template:
    metadata:
      labels:
        app: apache-kafka
    spec:
      containers:
      - name: apache-kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        - containerPort: 9094
        env:
          - name: KAFKA_BROKER_ID
            value: "0"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INTERNAL://kafka-service:9092,EXTERNAL://localhost:9094"
          - name: KAFKA_LISTENERS
            value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INTERNAL"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-data
        emptyDir: {}