apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      initContainers:
      - name: init-taskmanager
        image: apache/flink:1.16.0
        command: [ 'sh', '-c', 'mkdir -p /beam-java-files/apache/beam_java' ]
        volumeMounts:
          - name: beam-java-files
            mountPath: /beam-java-files
      - name: init-beam-java
        image: apache/beam_java8_sdk:2.41.0
        command: [ 'sh', '-c', 'cp -r /opt/apache/beam/* /beam-java-files/apache/beam_java/' ]
        volumeMounts:
          - name: beam-java-files
            mountPath: /beam-java-files
      containers:
      - name: taskmanager
        image: apache/flink:1.16.0
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: flink-writable-config-volume
          mountPath: /opt/flink/conf/writable
        - name: beam-java-files
          mountPath: /opt/apache
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      - name: beam-worker-pool
        image: apache/beam_python3.10_sdk
        args: ["--worker_pool"]
        ports:
        - containerPort: 50000
          name: pool
        livenessProbe:
          tcpSocket:
            port: 50000
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
          - name: beam-java-files
            mountPath: /opt/apache
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: flink-writable-config-volume
        emptyDir: { }
      - name: beam-java-files
        emptyDir: { }